#!/bin/zsh

git fetch -p
printf '\n'
git branch -vv
printf '\n'
git worktree prune
printf '\n'
for branch in $(git branch -vv | awk '{print $1,$4}' | grep 'gone]' | awk '{print $1}'); do
    echo git branch -D "$branch"
    git branch -D "$branch"
done
